// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Clase_11_12.Domain.Entities;

public partial class Ranking
{
    public int IdRanking { get; set; }

    public int? IdPelicula { get; set; }

    public int? Ranking1 { get; set; }

    public DateTime? Fecha { get; set; }

    public virtual Pelicula IdPeliculaNavigation { get; set; }
}